# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b28bacbe3759d86dc362fb617f9d011ec6dc52b26fbe145af40e06d14b982100e9ce03b7d6a26aed3b3618704210f9973ee6ade88ec96ecad41d0251900aeba

test:
  secret_key_base: c133cf2d6efbff62fd535811ca64b1f16003b86f2ef577633bc9762505b78724eedbc2db7bf2069f10c7bb050de07add6b455681bc116f4be11e94453111fcea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
